config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    post "/users/sessions/verify_otp" => "users/sessions#verify_otp"
  end

  root to: "pages#home"
  get '/venue-registration' => 'pages#venue_registration', as: :pages_venue_registration
  get '/not-found' => 'pages#not_found', as: :pages_not_found

  post '/venue-registration' => 'venue_application_form#create', as: :venue_application_form_create
  post '/venue-registration/:id' => 'venue_application_form#update', as: :venue_application_form_update
  get '/venue-registration/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_get_by_token
  get '/venue-form/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_venue_form_token
  get '/venue-form' => 'venue_application_form#venue_form', as: :venue_application_form_venue_form
  post '/venue-form/send-form-link-to-email/:token' => 'venue_application_form#send_form_link_to_email', as: :venue_application_form_send_form_link_to_email
  post '/venue-form/:token/director-sign' => 'venue_application_form#director_sign', as: :venue_application_form_director_sign
  get '/venue-form/success' => 'venue_application_form#venue_form_success', as: :venue_application_form_venue_form_success
  delete '/venue-registration/:id' => 'venue_application_form#destroy', as: :venue_application_form_destroy

  post '/directors/upload-front-license-file' => 'directors#upload_front_license_file', as: :directors_upload_front_license_file
  post '/directors/upload-back-license-file' => 'directors#upload_back_license_file', as: :directors_upload_back_license_file

  post '/abn/abn-details' => 'abn#abn_details', as: :abn_abn_details

  get '/terms_of_use' => 'pages#terms_of_use', as: :terms_of_use
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/faq' => 'pages#faq', as: :faq

  post '/contact' => 'contact#create', as: :contacts
  post 'contact/create' => 'contact#create', as: :contacts_create_contact

  scope :users do
    post '/create-users' => 'user#create_users', as: :users_create_users
    get '/set-password' => 'user#set_password', as: :users_set_password
    get '/set-password/:id' => 'user#edit_password', as: :users_edit_password
    post '/set-password/:id' => 'user#update_password', as: :users_update_password
  end

  namespace :admin do
    get '/' => 'dashboard#index', as: :admin_index
    get '/dashboard/' => 'dashboard#index', as: :admin_dashboard_index

    resources :users
    resources :email_templates
    resources :market_segments
    resources :credit_limits, except: [:show]

    get '/trading_terms_settings' => 'trading_terms_settings#index', as: :trading_terms_settings
    post '/update_trading_terms_settings' => 'trading_terms_settings#update', as: :update_trading_terms_settings

    resources :venue_suppliers, except: [:show]
    get '/set_supplier' => 'venue_suppliers#set_supplier', as: :set_supplier_venue_suppliers
    post '/venue_suppliers/:id/update' => 'venue_suppliers#update_ascf', as: :venue_suppliers_update_ascf
    post '/venue_suppliers/:id/pg-sign' => 'venue_suppliers#personal_guarantee_sign', as: :venue_suppliers_personal_guarantee_sign
    get '/set_vaf' => 'venue_suppliers#set_vaf', as: :set_vaf_venue_suppliers
    get '/get_director_details' => 'venue_suppliers#get_director_details', as: :venue_suppliers_get_director_details
    get '/get_vaf_directors' => 'venue_suppliers#get_vaf_directors', as: :venue_suppliers_get_vaf_directors
    get '/set_trading_term_setting' => 'venue_suppliers#set_trading_term_setting', as: :set_trading_term_setting_venue_suppliers
    get '/search_suppliers' => 'venue_suppliers#search_suppliers', as: :venue_suppliers_search_suppliers

    get '/venue_details' => 'venues#index', as: :venue_details
    post '/venues/import' => 'venues#import', as: :admin_import_venues
    post '/venues/admin_export' => 'venues#export', as: :admin_export_venues
    post '/venues/send_email_directors/:id' => 'venues#send_email_directors', as: :admin_venues_send_email_directors
    post '/venues/send_email_pgs/:id' => 'venues#send_email_pgs', as: :admin_venues_send_email_pgs
    get '/venues/approve/:id' => 'venues#approve', as: :admin_venues_approve
    get '/venues/reject/:id' => 'venues#reject', as: :admin_venues_reject
    post '/venues/send_credit_limit/:id' => 'venues#send_credit_limit', as: :admin_venues_send_credit_limit

    get '/venue_users' => 'venue_users#index', as: :venue_users
    get '/venue_users/:id' => 'venue_users#show', as: :show_venue_user

    get '/my_profile' => 'user_profiles#index', as: :admin_user_profile
    post '/update_director/:id' => 'user_profiles#update_director', as: :admin_update_director
    post '/update_personal_guarantee/:id' => 'user_profiles#update_personal_guarantee', as: :admin_update_personal_guarantee
    post '/update_admin/:id' => 'user_profiles#update_admin', as: :admin_update_admin
    post '/update_avatar/:id' => 'user_profiles#update_avatar', as: :user_profiles_update_avatar

    get '/pencil_terms_conditions' => 'pencil_terms_conditions#index', as: :pencil_terms_conditions
    post '/pencil_terms_conditions/:id/update' => 'pencil_terms_conditions#update', as: :pencil_terms_conditions_update

    resources :suppliers
    get '/suppliers_new_terms_and_condition' => 'suppliers#new_terms_and_condition', as: :suppliers_new_terms_and_condition
    get '/suppliers_my_terms_and_conditions' => 'suppliers#my_terms_and_conditions', as: :suppliers_my_terms_and_conditions
    post '/suppliers_create_terms_and_condition' => 'suppliers#create_terms_and_condition', as: :suppliers_create_terms_and_condition
    get '/suppliers_edit_terms_and_condition/:id' => 'suppliers#edit_terms_and_condition', as: :suppliers_edit_terms_and_condition
    post '/suppliers_update_terms_and_condition/:id' => 'suppliers#update_terms_and_condition', as: :suppliers_update_terms_and_condition
    delete '/suppliers_destroy_terms_and_condition/:id' => 'suppliers#destroy_terms_and_condition', as: :suppliers_destroy_terms_and_condition
    get '/suppliers_edit_supplier_user/:id' => 'suppliers#edit_supplier_user', as: :suppliers_edit_supplier_user
    get '/suppliers_new_supplier_user' => 'suppliers#new_supplier_user', as: :suppliers_new_supplier_user
    post '/suppliers_update_supplier_user/:id' => 'suppliers#update_supplier_user', as: :suppliers_update_supplier_user
    post '/suppliers_create_supplier_user' => 'suppliers#create_supplier_user', as: :suppliers_create_supplier_user
    delete '/suppliers_destroy_supplier_user/:id' => 'suppliers#destroy_supplier_user', as: :suppliers_destroy_supplier_user
    get '/suppliers_my_profile' => 'suppliers#my_profile', as: :suppliers_my_profile
    get '/suppliers_supplier_users' =>  'suppliers#supplier_users', as: :suppliers_supplier_users
    post '/suppliers_update_profile' => 'suppliers#update_profile', as: :suppliers_update_profile
    post '/suppliers_update_avatar/:id' => 'suppliers#update_avatar', as: :suppliers_update_avatar
    post '/suppliers_update_logo/:id' => 'suppliers#update_logo', as: :suppliers_update_logo
  end

  get '*path', :to => 'pages#not_found'
end

app/models/credit_limit.rb
class CreditLimit < ApplicationRecord
  belongs_to :supplier
  belongs_to :market_segment
  belongs_to :trading_terms_setting

  validate :validate_credit_limit, :validate_increments

  def validate_credit_limit
    unless validate_currency(credit_limit)
      errors.add(:credit_limit, 'Invalid value!')
    end
  end

  def validate_increments
    unless validate_currency(increments)
      errors.add(:increments, 'Invalid value!')
    end
  end

  def validate_currency(currency, precision = 15)
    currency.to_s.gsub(".", "").length <= precision
  end

  def self.set_market_segment(credit_limit_attrs, credit_limit_params)
    if credit_limit_params[:market_segment_id].include?("All")
      return credit_limit_attrs.merge(
        market_segment_id: MarketSegment.order(name: :asc).first[:id]
      )
    end

    credit_limit_attrs.merge(
      is_all_market_segments: false,
      market_segment_id: credit_limit_params[:market_segment_id]
    )
  end

  def self.set_trading_terms_setting(credit_limit_attrs, credit_limit_params, trading_terms_setting_id)
    if credit_limit_params[:trading_terms_setting_id].include?("All")
      return credit_limit_attrs.merge(
        trading_terms_setting_id: trading_terms_setting_id
      )
    end

    credit_limit_attrs.merge(
      is_all_trading_terms: false,
      trading_terms_setting_id: credit_limit_params[:trading_terms_setting_id]
    )
  end
end

app/controllers/admin/credit_limits_controller.rb
# Credit Limits Controller
class Admin::CreditLimitsController < Admin::AdminController
  before_action :authorize_supplier!
  before_action :set_title
  before_action :set_supplier, except: [:destroy]
  before_action :set_credit_limit, only: [:edit, :update, :destroy]
  before_action :set_trading_terms, only: [:new, :create, :edit, :update]

  def index
    @credit_limits = @supplier.credit_limits
  end

  def new
    @credit_limit = @supplier.credit_limits.new
  end

  def create
    credit_limit_attrs = credit_limit_attributes(@trading_terms_settings)
    credit_limit = @supplier.credit_limits.new(credit_limit_attrs)

    if credit_limit.save
      redirect_to admin_credit_limits_url, notice: 'Credit limit was successfully created.'
    else
      redirect_to admin_credit_limits_url, notice: 'Credit limit was not successfully created.'
    end
  end

  def edit
  end

  def update
    credit_limit_attrs = credit_limit_attributes(@trading_terms_settings)

    if @credit_limit.update(credit_limit_attrs)
      redirect_to admin_credit_limits_path, notice: 'Credit limit was successfully updated.'
    else
      redirect_to admin_credit_limits_path, notice: 'Credit limit was not successfully updated.'
    end
  end

  def destroy
    @credit_limit.destroy
    redirect_to admin_credit_limits_path, notice: 'Credit limit was successfully deleted.'
  end

  private

  def set_title
    $current_page = 'Pencil | Credit Limits'
    $subheader_title = 'Credit Limits'
  end

  def set_supplier
    @supplier = current_user.supplier
  end

  def set_trading_terms
    @trading_terms_settings = @supplier.trading_terms_settings.order(created_at: :asc)
  end

  def set_credit_limit
    param_id = params['id']
    @credit_limit = CreditLimit.find(param_id) if param_id.present?
  end

  def credit_limit_params
    params.require(:credit_limit).permit(
      :credit_limit, :increments, :market_segment_id, :trading_terms_setting_id
    )
  end

  def credit_limit_attributes(trading_terms_settings)
    credit_limit_attrs = {
      credit_limit: credit_limit_params[:credit_limit],
      increments: credit_limit_params[:increments]
    }

    credit_limit_attrs = CreditLimit.set_market_segment(credit_limit_attrs, credit_limit_params)
    CreditLimit.set_trading_terms_setting(credit_limit_attrs, credit_limit_params, trading_terms_settings.first[:id])
  end
end

app/views/admin/credit_limits/_form.html.erb
<%= form_with(model: credit_limit, local: true, url: url,
  html: { class: "m-form m-form--state m-form--fit", id: "new_credit_limit_form" }) do |form| %>
  <div class="m-portlet__body">
    <div class="m-form__section--first">
      <%
      hide_error = 'm--hide'
      hide_error = '' if credit_limit.errors.any?
      %>
      <div class="m-form__content">
        <div class="m-alert m-alert--icon alert alert-danger <%= hide_error %>" role="alert" id="m_form_1_msg">
          <div class="m-alert__icon">
            <i class="la la-warning"></i>
          </div>
          <div class="m-alert__text">
            <% if credit_limit.errors.any? %>
              <ul>
              <% credit_limit.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% else %>
              Oh snap! Change a few things up and try submitting again.
            <% end %>
          </div>
          <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
          </div>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-lg-12">
          <%= form.label :credit_limit, "* Credit limit:", class: 'form-control-label' %>
          <%= form.text_field :credit_limit, id: :credit_limit, class: 'form-control m-input currency text-align-left', placeholder: 'Credit limit' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-lg-6">
          <%= form.label :increments, "* Increments:", class: 'form-control-label' %>
          <%= form.text_field :increments, id: :increments, class: 'form-control m-input currency text-align-left', placeholder: 'Increments' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-lg-6">
          <%
            market_segments_options = []
            market_segments_options << [ "All", "All" ]

            MarketSegment.all.each do |market_segment|
              market_segments_options << [ market_segment[:name], market_segment[:id] ]
            end

            selected_market_segment = credit_limit[:market_segment_id] if !credit_limit[:is_all_market_segments]
            selected_market_segment = "All" if credit_limit[:is_all_market_segments]
          %>

          <%= form.label :market_segment_id, "* Market Segments:", class: 'form-control-label' %>
          <%= form.select(:market_segment_id,
                        options_for_select(market_segments_options, selected: selected_market_segment), {},
                        { class: 'form-control m-input m-select2', id: "market_segments_select" }) %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-lg-6">
          <%
            trading_terms_options = []
            trading_terms_options << [ "All", "All" ]

            trading_terms_settings.each do |trading_term|
              trading_terms_options << [ trading_term[:trading_term], trading_term[:id] ]
            end

            selected_trading_term = credit_limit[:trading_terms_setting_id] if !credit_limit[:is_all_trading_terms]
            selected_trading_term = "All" if credit_limit[:is_all_trading_terms]
          %>

          <%= form.label :trading_terms_setting_id, "* Trading Terms:", class: 'form-control-label' %>
          <%= form.select(:trading_terms_setting_id,
                        options_for_select(trading_terms_options, selected: selected_trading_term), {},
                        { class: 'custom-select m-input form-control', id: "trading_terms_select" }) %>
        </div>
      </div>
    </div>
  </div>
  <div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions m-form__actions">
      <div class="row">
        <div class="col-lg-12">
          <button type="submit" class="btn btn-brand">
            Save
          </button>
          <a href="<%= admin_credit_limits_path %>" class="btn btn-secondary">Cancel</a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/credit_limits/edit.html.erb
<div class='m-portlet m-portlet--mobile'>
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <h3 class="m-portlet__head-text">
          Edit Credit Limit
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body">
    <%= render 'form', credit_limit: @credit_limit, url: admin_credit_limit_path(params[:id]), trading_terms_settings: @trading_terms_settings %>
  </div>
</div>

app/views/admin/credit_limits/index.html.erb
<div class='m-portlet m-portlet--mobile'>
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <span class="m-portlet__head-icon">
          <i class="flaticon-coins"></i>
        </span>
        <h3 class="m-portlet__head-text">
          List of Credit Limits (AUD)
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body">
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
      <div class="row align-items-center">
        <div class="col-xl-8 order-2 order-xl-1"> <!--
          <div class="form-group m-form__group row align-items-center">
            <div class="col-md-4">
              <div class="m-input-icon m-input-icon--left">
                <input type="text" class="form-control m-input" placeholder="Search..." id="generalSearch">
                <span class="m-input-icon__icon m-input-icon__icon--left">
                  <span><i class="la la-search"></i></span>
                </span>
              </div>
            </div>
          </div> -->
        </div>
        <div class="col-xl-4 order-1 order-xl-2 m--align-right">
          <a href="<%= new_admin_credit_limit_path %>" class="btn btn-danger m-btn m-btn--custom m-btn--icon m-btn--air" >
            <span>
              <i class="la la-plus"></i>
              <span>New Credit Limit</span>
            </span>
          </a>
          <div class="m-separator m-separator--dashed d-xl-none"></div>
        </div>
      </div>
    </div>
    <table class="m-datatable text-center" id="credit_limits_table" width="100%">
      <thead>
        <tr>
          <th title="No">#</th>
          <th title="Credit Limit">Credit Limit</th>
          <th title="Increments">Increments</th>
          <th title="Market Segment">Market Segment</th>
          <th title="Trading Term">Trading Term</th>
          <th title="Actions">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @credit_limits.each_with_index do |credit_limit, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= number_to_currency(credit_limit[:credit_limit], unit: "", separator: ".", delimiter: ",", precision: 0) %></td>
            <td><%= number_to_currency(credit_limit[:increments], unit: "", separator: ".", delimiter: ",", precision: 0) %></td>
            <td>
              <%= credit_limit[:is_all_market_segments] ? "All" : credit_limit.market_segment[:name] %>
            </td>
            <td>
              <%= credit_limit[:is_all_trading_terms] ? "All" : credit_limit.trading_terms_setting[:trading_term] %>
            </td>
            <td>
              <a href="<%= edit_admin_credit_limit_path(credit_limit) %>" class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill" title="Edit">
                <i class="la la-edit"></i>
              </a>
              <a href="<%= admin_credit_limit_path(credit_limit[:id]) %>" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill"
                title="Delete" action="destroy" data-confirm="Are you sure?" rel="nofollow" data-method="delete">
                <i class="la la-trash"></i>
              </a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/credit_limits/new.html.erb
<div class='m-portlet m-portlet--mobile'>
  <div class="m-portlet__head">
    <div class="m-portlet__head-caption">
      <div class="m-portlet__head-title">
        <h3 class="m-portlet__head-text">
          New Credit Limit
        </h3>
      </div>
    </div>
  </div>
  <div class="m-portlet__body">
    <%= render 'form', credit_limit: @credit_limit, url: admin_credit_limits_path, trading_terms_settings: @trading_terms_settings %>
  </div>
</div>