config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    post "/users/sessions/verify_otp" => "users/sessions#verify_otp"
  end

  root to: "pages#home"
  get '/venue-registration' => 'pages#venue_registration', as: :pages_venue_registration
  get '/not-found' => 'pages#not_found', as: :pages_not_found

  post '/venue-registration' => 'venue_application_form#create', as: :venue_application_form_create
  post '/venue-registration/:id' => 'venue_application_form#update', as: :venue_application_form_update
  get '/venue-registration/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_get_by_token
  get '/venue-form/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_venue_form_token
  get '/venue-form' => 'venue_application_form#venue_form', as: :venue_application_form_venue_form
  post '/venue-form/send-form-link-to-email/:token' => 'venue_application_form#send_form_link_to_email', as: :venue_application_form_send_form_link_to_email
  post '/venue-form/:token/director-sign' => 'venue_application_form#director_sign', as: :venue_application_form_director_sign
  get '/venue-form/success' => 'venue_application_form#venue_form_success', as: :venue_application_form_venue_form_success
  delete '/venue-registration/:id' => 'venue_application_form#destroy', as: :venue_application_form_destroy

  post '/directors/upload-front-license-file' => 'directors#upload_front_license_file', as: :directors_upload_front_license_file
  post '/directors/upload-back-license-file' => 'directors#upload_back_license_file', as: :directors_upload_back_license_file

  post '/abn/abn-details' => 'abn#abn_details', as: :abn_abn_details

  get '/terms_of_use' => 'pages#terms_of_use', as: :terms_of_use
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/faq' => 'pages#faq', as: :faq

  post '/contact' => 'contact#create', as: :contacts
  post 'contact/create' => 'contact#create', as: :contacts_create_contact

  scope :users do
    post '/create-users' => 'user#create_users', as: :users_create_users
    get '/set-password' => 'user#set_password', as: :users_set_password
    get '/set-password/:id' => 'user#edit_password', as: :users_edit_password
    post '/set-password/:id' => 'user#update_password', as: :users_update_password
  end

  namespace :admin do
    get '/' => 'dashboard#index', as: :admin_index
    get '/dashboard/' => 'dashboard#index', as: :admin_dashboard_index

    resources :users
    resources :email_templates
    resources :market_segments
    resources :credit_limits, except: [:show]

    get '/trading_terms_settings' => 'trading_terms_settings#index', as: :trading_terms_settings
    post '/update_trading_terms_settings' => 'trading_terms_settings#update', as: :update_trading_terms_settings

    resources :venue_suppliers, except: [:show]
    get '/set_supplier' => 'venue_suppliers#set_supplier', as: :set_supplier_venue_suppliers
    post '/venue_suppliers/:id/update' => 'venue_suppliers#update_ascf', as: :venue_suppliers_update_ascf
    post '/venue_suppliers/:id/pg-sign' => 'venue_suppliers#personal_guarantee_sign', as: :venue_suppliers_personal_guarantee_sign
    get '/set_vaf' => 'venue_suppliers#set_vaf', as: :set_vaf_venue_suppliers
    get '/get_director_details' => 'venue_suppliers#get_director_details', as: :venue_suppliers_get_director_details
    get '/get_vaf_directors' => 'venue_suppliers#get_vaf_directors', as: :venue_suppliers_get_vaf_directors
    get '/set_trading_term_setting' => 'venue_suppliers#set_trading_term_setting', as: :set_trading_term_setting_venue_suppliers
    get '/search_suppliers' => 'venue_suppliers#search_suppliers', as: :venue_suppliers_search_suppliers

    get '/venue_details' => 'venues#index', as: :venue_details
    post '/venues/import' => 'venues#import', as: :admin_import_venues
    post '/venues/admin_export' => 'venues#export', as: :admin_export_venues
    post '/venues/send_email_directors/:id' => 'venues#send_email_directors', as: :admin_venues_send_email_directors
    post '/venues/send_email_pgs/:id' => 'venues#send_email_pgs', as: :admin_venues_send_email_pgs
    get '/venues/approve/:id' => 'venues#approve', as: :admin_venues_approve
    get '/venues/reject/:id' => 'venues#reject', as: :admin_venues_reject
    post '/venues/send_credit_limit/:id' => 'venues#send_credit_limit', as: :admin_venues_send_credit_limit

    get '/venue_users' => 'venue_users#index', as: :venue_users
    get '/venue_users/:id' => 'venue_users#show', as: :show_venue_user

    get '/my_profile' => 'user_profiles#index', as: :admin_user_profile
    post '/update_director/:id' => 'user_profiles#update_director', as: :admin_update_director
    post '/update_personal_guarantee/:id' => 'user_profiles#update_personal_guarantee', as: :admin_update_personal_guarantee
    post '/update_admin/:id' => 'user_profiles#update_admin', as: :admin_update_admin
    post '/update_avatar/:id' => 'user_profiles#update_avatar', as: :user_profiles_update_avatar

    get '/pencil_terms_conditions' => 'pencil_terms_conditions#index', as: :pencil_terms_conditions
    post '/pencil_terms_conditions/:id/update' => 'pencil_terms_conditions#update', as: :pencil_terms_conditions_update

    resources :suppliers
    get '/suppliers_new_terms_and_condition' => 'suppliers#new_terms_and_condition', as: :suppliers_new_terms_and_condition
    get '/suppliers_my_terms_and_conditions' => 'suppliers#my_terms_and_conditions', as: :suppliers_my_terms_and_conditions
    post '/suppliers_create_terms_and_condition' => 'suppliers#create_terms_and_condition', as: :suppliers_create_terms_and_condition
    get '/suppliers_edit_terms_and_condition/:id' => 'suppliers#edit_terms_and_condition', as: :suppliers_edit_terms_and_condition
    post '/suppliers_update_terms_and_condition/:id' => 'suppliers#update_terms_and_condition', as: :suppliers_update_terms_and_condition
    delete '/suppliers_destroy_terms_and_condition/:id' => 'suppliers#destroy_terms_and_condition', as: :suppliers_destroy_terms_and_condition
    get '/suppliers_edit_supplier_user/:id' => 'suppliers#edit_supplier_user', as: :suppliers_edit_supplier_user
    get '/suppliers_new_supplier_user' => 'suppliers#new_supplier_user', as: :suppliers_new_supplier_user
    post '/suppliers_update_supplier_user/:id' => 'suppliers#update_supplier_user', as: :suppliers_update_supplier_user
    post '/suppliers_create_supplier_user' => 'suppliers#create_supplier_user', as: :suppliers_create_supplier_user
    delete '/suppliers_destroy_supplier_user/:id' => 'suppliers#destroy_supplier_user', as: :suppliers_destroy_supplier_user
    get '/suppliers_my_profile' => 'suppliers#my_profile', as: :suppliers_my_profile
    get '/suppliers_supplier_users' =>  'suppliers#supplier_users', as: :suppliers_supplier_users
    post '/suppliers_update_profile' => 'suppliers#update_profile', as: :suppliers_update_profile
    post '/suppliers_update_avatar/:id' => 'suppliers#update_avatar', as: :suppliers_update_avatar
    post '/suppliers_update_logo/:id' => 'suppliers#update_logo', as: :suppliers_update_logo
  end

  get '*path', :to => 'pages#not_found'
end

app/controllers/admin/user_profiles_controller.rb
class Admin::UserProfilesController < Admin::AdminController
  before_action :authorize_profile_user!, only: [:index]
  before_action :set_title

  def index
    if current_user.is_admin?
      @user = current_user
    elsif current_user.is_director?
      @director = current_user.directors.first
    elsif current_user.is_personal_guarantee?
      @personal_guarantee = current_user.personal_guarantees.first
    end
  end

  def update_admin
    user = User.find(params[:id]) if params[:id].present?

    respond_to do |format|
      if user.present? && user.update(admin_params)
        format.html { redirect_to admin_admin_user_profile_path, notice: 'Your profile was successfully updated.' }
      else
        flash[:alert] = user.errors.full_messages.to_sentence
        format.html { redirect_to admin_admin_user_profile_path }
        format.json { render json: user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_director
    director = Director.find(params[:id]) if params[:id].present?
    # Filter Director attributes and director user password by remove blank fields
    user_attributes = director_params.permit(:password, :password_confirmation).reject { |_, v| v.blank? }

    director_attributes = director_params.permit(
      :firstname, :middlename, :lastname, :date_of_birth, :email, :address_line_1, :address_line_2, :mobile, :phone,
      :drivers_license_number, :license_expiry
    ).reject { |_, v| v.blank? }

    respond_to do |format|
      if !director.blank? && director.update(director_attributes) && director.user.update(user_attributes)
        format.html { redirect_to admin_admin_user_profile_path, notice: 'Your profile was successfully updated.' }
      else
        flash[:alert] = (director.errors.full_messages + director.user.errors.full_messages).to_sentence
        format.html { redirect_to admin_admin_user_profile_path }
        format.json { render json: director.errors + director.user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_personal_guarantee
    personal_guarantee = PersonalGuarantee.find(params[:id]) if params[:id].present?
    # Filter Director attributes and director user password by remove blank fields
    user_attributes = pg_params.permit(:password, :password_confirmation).reject { |_, v| v.blank? }

    pg_attributes = pg_params.permit(
      :firstname, :lastname, :email, :mobile, :phone, :home_address_line_1, :home_address_line_2
    ).reject { |_, v| v.blank? }

    respond_to do |format|
      if !personal_guarantee.blank? && personal_guarantee.update(pg_attributes) &&
         personal_guarantee.user.update(user_attributes)
        format.html { redirect_to admin_admin_user_profile_path, notice: 'Your profile was successfully updated.' }
      else
        full_message = personal_guarantee.errors.full_messages + personal_guarantee.user.errors.full_messages
        full_errors = personal_guarantee.errors + personal_guarantee.user.errors
        flash[:alert] = full_message.to_sentence
        format.html { redirect_to admin_admin_user_profile_path }
        format.json { render json: full_errors, status: :unprocessable_entity }
      end
    end
  end

  def update_avatar
    if params[:user].blank?
      redirect_to admin_admin_user_profile_path, notice: 'Your Avatar does not change.'
      return
    end

    if current_user.update(user_avatar_params)
      if user_avatar_params[:avatar].blank?
        message = 'Your Avatar was successfully updated.'
      else
        message = 'Your Avatar was cropped successfully.'
      end
    else
      message = 'Your Avatar was not successfully updated.'
    end

    redirect_to admin_admin_user_profile_path, notice: message
  end

  private

  def set_title
    $current_page = 'Pencil | My Profile'
    $subheader_title = 'My Profile'
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_params
    params.require(:user).permit(
      :name, :firstname, :lastname, :email, :password, :password_confirmation
    ).reject { |_, v| v.blank? }
  end

  def director_params
    params.require(:director)
  end

  def pg_params
    params.require(:personal_guarantee)
  end

  def user_avatar_params
    params.require(:user).permit(:avatar, :crop_x, :crop_y, :crop_w, :crop_h)
  end

  def authorize_profile_user!
    unless current_user.is_admin? || current_user.is_director? || current_user.is_personal_guarantee?
      redirect_to admin_venue_details_url
    end
  end
end

app/views/admin/user_profiles/_admin.html.erb
<%= form_with(model: user, local: true, method: :post, url: url,
  html: { class: "m-form m-form--fit m-form--label-align-right", id: "update_admin_user_form" }) do |form| %>
  <div class="m-portlet__body">
    <div class="m-form__section m-form__section--first">
      <%
      hide_error = 'm--hide'
      hide_error = '' if user.errors.any?
      %>
      <div class="m-form__content">
        <div class="m-alert m-alert--icon alert alert-danger <%= hide_error %>" role="alert" id="update_admin_user_form_msg">
          <div class="m-alert__icon">
            <i class="la la-warning"></i>
          </div>
          <div class="m-alert__text">
            <% if user.errors.any? %>
              <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% else %>
              Oh snap! Change a few things up and try submitting again.
            <% end %>
          </div>
          <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
          </div>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="col-md-12 ml-auto">
          <h3 class="m-form__section">
            1. User Details
          </h3>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :name, "Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :name, id: :name, class: 'form-control m-input', placeholder: 'Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :firstname, "First Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :firstname, id: :firstname, class: 'form-control m-input', placeholder: 'First Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :lastname, "Last Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :lastname, id: :lastname, class: 'form-control m-input', placeholder: 'Last Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :email, "Email", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :email, id: :email, class: 'form-control m-input', placeholder: 'Email', readonly: true %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="col-md-12 ml-auto">
          <h3 class="m-form__section">
            2. Password
          </h3>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :password, "New password", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.password_field :password, id: :password, class: 'form-control m-input password', placeholder: 'New password'%>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :password_confirmation, "Confirm password", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.password_field :password_confirmation, id: :password_confirmation, class: 'form-control m-input', placeholder: 'Confirm password'%>
        </div>
      </div>
    </div>
  </div>
  <div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions m-form__actions">
      <div class="row m--align-center">
        <div class="col-lg-12">
          <button id="submit" type="submit" class="btn btn-brand">
            Save
          </button>
          <button type="button" onclick="location.href='<%= admin_admin_index_path %>';" class="btn btn-secondary">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/user_profiles/_director.html.erb
<%= form_with(model: director, local: true, method: :post, url: url,
  html: { class: "m-form m-form--fit m-form--label-align-right", id: "update_admin_director_form" }) do |form| %>
  <div class="m-portlet__body">
    <div class="m-form__section m-form__section--first">
      <%
      hide_error = 'm--hide'
      hide_error = '' if director.errors.any?
      %>
      <div class="m-form__content">
        <div class="m-alert m-alert--icon alert alert-danger <%= hide_error %>" role="alert" id="update_admin_director_form_msg">
          <div class="m-alert__icon">
            <i class="la la-warning"></i>
          </div>
          <div class="m-alert__text">
            <% if director.errors.any? %>
              <ul>
              <% director.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% else %>
              Oh snap! Change a few things up and try submitting again.
            <% end %>
          </div>
          <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
          </div>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="col-md-12 ml-auto">
          <h3 class="m-form__section">
            1. Director Details
          </h3>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :firstname, "First Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :firstname, id: :firstname, class: 'form-control m-input', placeholder: 'First Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :middlename, "Middle Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :middlename, id: :middlename, class: 'form-control m-input', placeholder: 'Middle Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :lastname, "Last Name", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :lastname, id: :lastname, class: 'form-control m-input', placeholder: 'Last Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :date_of_birth, "Date of Birth", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :date_of_birth, id: :date_of_birth, class: 'form-control m-input date_picker', placeholder: 'Date of Birth', value: "#{pretty_format_date(director[:date_of_birth], '%d/%m/%Y')}" %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :email, "Email", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :email, id: :email, class: 'form-control m-input', placeholder: 'Email', readonly: true %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :mobile, "Mobile", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :mobile, id: :mobile, class: 'form-control m-input mobileAU', placeholder: 'Mobile' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :phone, "Phone", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :phone, id: :phone, class: 'form-control m-input phoneAU', placeholder: 'Phone' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :drivers_license_number, "Driver's License", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :drivers_license_number, id: :drivers_license_number, class: 'form-control m-input', placeholder: "Driver's License" %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :license_expiry, "License Expiry", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :license_expiry, id: :license_expiry, class: 'form-control m-input date_picker', placeholder: 'License Expiry', value: "#{pretty_format_date(director[:license_expiry], '%d/%m/%Y')}" %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :address, "Address", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.text_field :address_line_1, id: :address_line_1, class: 'form-control m-input address-line-1', placeholder: 'Address Line 1', value: director[:address_line_1].blank? ? "#{director[:street_number]} #{director[:street_name]} #{director[:street_type]}" : director[:address_line_1] %>
          <%= form.text_field :address_line_2, id: :address_line_2, class: 'form-control m-input', placeholder: 'Address Line 2', value: director[:address_line_2].blank? ? "#{director[:suburb]} #{director[:state]} #{director[:postcode]}" :  director[:address_line_2]  %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="col-md-12 ml-auto">
          <h3 class="m-form__section">
            2. Password
          </h3>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :password, "New password", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.password_field :password, id: :password, class: 'form-control m-input password', placeholder: 'New password'%>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <%= form.label :password_confirmation, "Confirm password", class: 'col-lg-3 col-form-label' %>
        <div class="col-lg-9">
          <%= form.password_field :password_confirmation, id: :password_confirmation, class: 'form-control m-input', placeholder: 'Confirm password'%>
        </div>
      </div>
    </div>
  </div>
  <div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions m-form__actions">
      <div class="row m--align-center">
        <div class="col-lg-12">
          <button id="submit" type="submit" class="btn btn-brand">
            Save
          </button>
          <button type="button" onclick="location.href='<%= admin_admin_index_path %>';" class="btn btn-secondary">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/user_profiles/index.html.erb
<div class="m-content">
  <div class="row">
    <div class="col-xl-3 col-lg-4">
      <div class="m-portlet m-portlet--full-height  ">
        <div class="m-portlet__body">
          <div class="m-card-profile">
            <div class="m-card-profile__title m--hide">
              Your Profile
            </div>
            <div class="m-card-profile__pic">
              <div class="m-card-profile__pic-wrapper">
                <img src="<%= current_user.default_avatar %>" class="m--img-rounded m--marginless" alt=""/>
              </div>
            </div>
            <div class="m-card-profile__details overflow-hidden">
              <% if current_user.is_admin? %>
                <span class="m-card-profile__name">
                  <%= "#{@user[:firstname]} #{@user[:lastname]}" %>
                </span>
                <a href="" class="m-card-profile__email m-link"><%= @user[:email] %></a>
              <% elsif current_user.is_director? && !@director.blank? %>
                <span class="m-card-profile__name">
                  <%= "#{@director[:firstname]} #{@director[:lastname]}" %>
                </span>
                <a href="" class="m-card-profile__email m-link"><%= @director[:email] %></a>
              <% elsif current_user.is_personal_guarantee? && !@personal_guarantee.blank? %>
                <span class="m-card-profile__name">
                  <%= "#{@personal_guarantee[:firstname]} #{@personal_guarantee[:lastname]}" %>
                </span>
                <a href="" class="m-card-profile__email m-link"><%= @personal_guarantee[:email] %></a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-9 col-lg-8">
      <div class="m-portlet m-portlet--full-height m-portlet--tabs  ">
        <div class="m-portlet__head">
          <div class="m-portlet__head-tools">
            <ul class="nav nav-tabs m-tabs m-tabs-line   m-tabs-line--left m-tabs-line--primary" role="tablist">
              <li class="nav-item m-tabs__item">
                <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_user_profile_tab_1" role="tab">
                  <i class="flaticon-share m--hide"></i>
                  Update Profile
                </a>
              </li>
              <li class="nav-item m-tabs__item">
                <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_user_profile_tab_2" role="tab">
                  Upload Avatar
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="tab-content">
          <div class="tab-pane active" id="m_user_profile_tab_1">
            <% if current_user.is_admin? %>
              <%= render 'admin', user: @user, url: admin_admin_update_admin_path(@user[:id]) %>
            <% elsif current_user.is_director? && !@director.blank? %>
              <%= render 'director', director: @director, url: admin_admin_update_director_path(@director[:id]) %>
            <% elsif current_user.is_personal_guarantee? && !@personal_guarantee.blank? %>
              <%= render 'personal_guarantee', personal_guarantee: @personal_guarantee, url: admin_admin_update_personal_guarantee_path(@personal_guarantee[:id]) %>
            <% end %>
          </div>
          <div class="tab-pane " id="m_user_profile_tab_2">
            <%= render '/shared/avatar', user: current_user, url: admin_user_profiles_update_avatar_path(current_user[:id]) %>
          </div>
          <div class="tab-pane " id="m_user_profile_tab_3"></div>
        </div>
      </div>
    </div>
  </div>
</div>