config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  devise_scope :user do
    post "/users/sessions/verify_otp" => "users/sessions#verify_otp"
  end

  root to: "pages#home"
  get '/venue-registration' => 'pages#venue_registration', as: :pages_venue_registration
  get '/not-found' => 'pages#not_found', as: :pages_not_found

  post '/venue-registration' => 'venue_application_form#create', as: :venue_application_form_create
  post '/venue-registration/:id' => 'venue_application_form#update', as: :venue_application_form_update
  get '/venue-registration/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_get_by_token
  get '/venue-form/token/:token' => 'venue_application_form#get_by_token', as: :venue_application_form_venue_form_token
  get '/venue-form' => 'venue_application_form#venue_form', as: :venue_application_form_venue_form
  post '/venue-form/send-form-link-to-email/:token' => 'venue_application_form#send_form_link_to_email', as: :venue_application_form_send_form_link_to_email
  post '/venue-form/:token/director-sign' => 'venue_application_form#director_sign', as: :venue_application_form_director_sign
  get '/venue-form/success' => 'venue_application_form#venue_form_success', as: :venue_application_form_venue_form_success
  delete '/venue-registration/:id' => 'venue_application_form#destroy', as: :venue_application_form_destroy

  post '/directors/upload-front-license-file' => 'directors#upload_front_license_file', as: :directors_upload_front_license_file
  post '/directors/upload-back-license-file' => 'directors#upload_back_license_file', as: :directors_upload_back_license_file

  post '/abn/abn-details' => 'abn#abn_details', as: :abn_abn_details

  get '/terms_of_use' => 'pages#terms_of_use', as: :terms_of_use
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/faq' => 'pages#faq', as: :faq

  post '/contact' => 'contact#create', as: :contacts
  post 'contact/create' => 'contact#create', as: :contacts_create_contact

  scope :users do
    post '/create-users' => 'user#create_users', as: :users_create_users
    get '/set-password' => 'user#set_password', as: :users_set_password
    get '/set-password/:id' => 'user#edit_password', as: :users_edit_password
    post '/set-password/:id' => 'user#update_password', as: :users_update_password
  end

  namespace :admin do
    get '/' => 'dashboard#index', as: :admin_index
    get '/dashboard/' => 'dashboard#index', as: :admin_dashboard_index

    resources :users
    resources :email_templates
    resources :market_segments
    resources :credit_limits, except: [:show]

    get '/trading_terms_settings' => 'trading_terms_settings#index', as: :trading_terms_settings
    post '/update_trading_terms_settings' => 'trading_terms_settings#update', as: :update_trading_terms_settings

    resources :venue_suppliers, except: [:show]
    get '/set_supplier' => 'venue_suppliers#set_supplier', as: :set_supplier_venue_suppliers
    post '/venue_suppliers/:id/update' => 'venue_suppliers#update_ascf', as: :venue_suppliers_update_ascf
    post '/venue_suppliers/:id/pg-sign' => 'venue_suppliers#personal_guarantee_sign', as: :venue_suppliers_personal_guarantee_sign
    get '/set_vaf' => 'venue_suppliers#set_vaf', as: :set_vaf_venue_suppliers
    get '/get_director_details' => 'venue_suppliers#get_director_details', as: :venue_suppliers_get_director_details
    get '/get_vaf_directors' => 'venue_suppliers#get_vaf_directors', as: :venue_suppliers_get_vaf_directors
    get '/set_trading_term_setting' => 'venue_suppliers#set_trading_term_setting', as: :set_trading_term_setting_venue_suppliers
    get '/search_suppliers' => 'venue_suppliers#search_suppliers', as: :venue_suppliers_search_suppliers

    get '/venue_details' => 'venues#index', as: :venue_details
    post '/venues/import' => 'venues#import', as: :admin_import_venues
    post '/venues/admin_export' => 'venues#export', as: :admin_export_venues
    post '/venues/send_email_directors/:id' => 'venues#send_email_directors', as: :admin_venues_send_email_directors
    post '/venues/send_email_pgs/:id' => 'venues#send_email_pgs', as: :admin_venues_send_email_pgs
    get '/venues/approve/:id' => 'venues#approve', as: :admin_venues_approve
    get '/venues/reject/:id' => 'venues#reject', as: :admin_venues_reject
    post '/venues/send_credit_limit/:id' => 'venues#send_credit_limit', as: :admin_venues_send_credit_limit

    get '/venue_users' => 'venue_users#index', as: :venue_users
    get '/venue_users/:id' => 'venue_users#show', as: :show_venue_user

    get '/my_profile' => 'user_profiles#index', as: :admin_user_profile
    post '/update_director/:id' => 'user_profiles#update_director', as: :admin_update_director
    post '/update_personal_guarantee/:id' => 'user_profiles#update_personal_guarantee', as: :admin_update_personal_guarantee
    post '/update_admin/:id' => 'user_profiles#update_admin', as: :admin_update_admin
    post '/update_avatar/:id' => 'user_profiles#update_avatar', as: :user_profiles_update_avatar

    get '/pencil_terms_conditions' => 'pencil_terms_conditions#index', as: :pencil_terms_conditions
    post '/pencil_terms_conditions/:id/update' => 'pencil_terms_conditions#update', as: :pencil_terms_conditions_update

    resources :suppliers
    get '/suppliers_new_terms_and_condition' => 'suppliers#new_terms_and_condition', as: :suppliers_new_terms_and_condition
    get '/suppliers_my_terms_and_conditions' => 'suppliers#my_terms_and_conditions', as: :suppliers_my_terms_and_conditions
    post '/suppliers_create_terms_and_condition' => 'suppliers#create_terms_and_condition', as: :suppliers_create_terms_and_condition
    get '/suppliers_edit_terms_and_condition/:id' => 'suppliers#edit_terms_and_condition', as: :suppliers_edit_terms_and_condition
    post '/suppliers_update_terms_and_condition/:id' => 'suppliers#update_terms_and_condition', as: :suppliers_update_terms_and_condition
    delete '/suppliers_destroy_terms_and_condition/:id' => 'suppliers#destroy_terms_and_condition', as: :suppliers_destroy_terms_and_condition
    get '/suppliers_edit_supplier_user/:id' => 'suppliers#edit_supplier_user', as: :suppliers_edit_supplier_user
    get '/suppliers_new_supplier_user' => 'suppliers#new_supplier_user', as: :suppliers_new_supplier_user
    post '/suppliers_update_supplier_user/:id' => 'suppliers#update_supplier_user', as: :suppliers_update_supplier_user
    post '/suppliers_create_supplier_user' => 'suppliers#create_supplier_user', as: :suppliers_create_supplier_user
    delete '/suppliers_destroy_supplier_user/:id' => 'suppliers#destroy_supplier_user', as: :suppliers_destroy_supplier_user
    get '/suppliers_my_profile' => 'suppliers#my_profile', as: :suppliers_my_profile
    get '/suppliers_supplier_users' =>  'suppliers#supplier_users', as: :suppliers_supplier_users
    post '/suppliers_update_profile' => 'suppliers#update_profile', as: :suppliers_update_profile
    post '/suppliers_update_avatar/:id' => 'suppliers#update_avatar', as: :suppliers_update_avatar
    post '/suppliers_update_logo/:id' => 'suppliers#update_logo', as: :suppliers_update_logo
  end

  get '*path', :to => 'pages#not_found'
end

app/controllers/admin/venue_suppliers_controller.rb
class Admin::VenueSuppliersController < Admin::AdminController
  before_action :authorize_director!, only: [:new, :update, :destroy, :update_ascf]
  before_action :authorize_venue_user!, only: [:edit]
  before_action :set_title
  before_action :set_venue_supplier, only: [:edit, :update, :destroy, :update_ascf]
  before_action :check_user_has_venues, only: [:new]
  before_action :set_apply_supplier_credit_form, only: [:new, :edit]

  def index
    @all_venues_status = ApplySupplierCreditForm.get_all_status
    @venue_suppliers = current_user.all_apply_supplier_credit_forms
  end

  def new
    @venue_supplier = ApplySupplierCreditForm.new
  end

  def edit
    return if check_any_pg_signed
    authorize_personal_guarantee! if params['step'] == ApplySupplierCreditForm::STEP_REVIEW
    @number_of_trade_references = @venue_supplier.trading_terms_setting.get_required_trade_references_quantity
    @number_of_personal_guarantees = @venue_supplier.trading_terms_setting.get_required_personal_guarantees_quantity
  end

  def update
  end

  def destroy
    @venue_supplier.destroy
    respond_to do |format|
      format.html { redirect_to admin_suppliers_url, notice: 'The supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    venue_credit_limit = params[:venue_credit_limit].delete(',')
    trading_terms_setting = TradingTermsSetting.where(id: params[:trading_terms_setting_id]).first
    is_save_and_continue = false

    if params['is_save_and_continue'].present?
      is_save_and_continue = CommonLib.convert_to_bool(params['is_save_and_continue'])
    end

    selected_directors_ids = params['selected_directors_ids'].present? ? params['selected_directors_ids'] : []
    selected_directors_ids.uniq!
    personal_guarantees_params = []

    if params['personal_guarantees'].present?
      personal_guarantees_params = params['personal_guarantees'].as_json.values
      is_pgs_params_a = personal_guarantees_params.instance_of?(Array)
      personal_guarantees_params = [] << personal_guarantees_params unless is_pgs_params_a
      personal_guarantees_params = ApplySupplierCreditForm.filter_pg_params(personal_guarantees_params)
    end

    pgs_quantity = Director.get_real_pg_quantity(selected_directors_ids, personal_guarantees_params)

    unless trading_terms_setting.has_enough_personal_guarantees(pgs_quantity) || is_save_and_continue
      message = 'The added personal guarantees have duplicate emails.'
      message += ' Please update it and try again!'

      respond_to do |format|
        format.json {
          render json: {
            apply_supplier_credit_form: nil,
            message: message
          },
          status: :unprocessable_entity
        }
      end

      return
    end

    @apply_supplier_credit_form = ApplySupplierCreditForm.create!(
      venue_supplier_params.merge(
        trading_terms_setting_id: params[:trading_terms_setting_id],
        venue_credit_limit: venue_credit_limit,
        credit_limit: venue_credit_limit,
        created_by_id: current_user[:id]
      )
    )

    if params['is_save_and_continue'].present?
      is_save_and_continue = CommonLib.convert_to_bool(params['is_save_and_continue'])
      @apply_supplier_credit_form[:status] = Const::STATUS[:draft][:value]
    else
      trading_terms_setting = @apply_supplier_credit_form.trading_terms_setting

      if trading_terms_setting[:personal_guarantees] == Const::SIGN_QUANTITIES[:none][:value]
        @apply_supplier_credit_form[:status] = Const::STATUS[:no_signature_required][:value]
        stc_content = @apply_supplier_credit_form.get_supplier_terms_condition[:content]
        @apply_supplier_credit_form[:supplier_terms_condition_content] = stc_content
      else
        @apply_supplier_credit_form[:status] = Const::STATUS[:pending_pg_signature][:value]
      end
    end

    respond_to do |format|
      if @apply_supplier_credit_form.save
        apply_supplier_credit_form = @apply_supplier_credit_form.as_json

        create_personal_guarantees(
          selected_directors_ids, personal_guarantees_params, @apply_supplier_credit_form, is_save_and_continue
        )

        save_trade_references(params, @apply_supplier_credit_form, is_save_and_continue)

        if is_save_and_continue == false
          UserMailer.ascf_apply_send_to_supplier(
            ascf: @apply_supplier_credit_form
          ).deliver_later
        end

        format.json {
          render json: {
            apply_supplier_credit_form: apply_supplier_credit_form,
            message: 'Your apply supplier credit has been created successfully',
            redirect_url:  admin_venue_suppliers_path
          },
          status: :created
        }
      else
        format.json {
          render json: {
            apply_supplier_credit_form: nil,
            message: @apply_supplier_credit_form.errors
          },
          status: :unprocessable_entity
        }
      end
    end
  end

  def update_ascf
    trading_terms_setting = TradingTermsSetting.where(id: params[:trading_terms_setting_id]).first
    is_save_and_continue = false

    if params['is_save_and_continue'].present?
      is_save_and_continue = CommonLib.convert_to_bool(params['is_save_and_continue'])
    end

    selected_directors_ids = params['selected_directors_ids'].present? ? params['selected_directors_ids'] : []
    selected_directors_ids.uniq!
    personal_guarantees_params = []

    if params['personal_guarantees'].present?
      personal_guarantees_params = params['personal_guarantees'].as_json.values
      is_pgs_params_a = personal_guarantees_params.instance_of?(Array)
      personal_guarantees_params = [] << personal_guarantees_params unless is_pgs_params_a
      personal_guarantees_params = ApplySupplierCreditForm.filter_pg_params(personal_guarantees_params)
    end

    pgs_quantity = Director.get_real_pg_quantity(selected_directors_ids, personal_guarantees_params)

    unless trading_terms_setting.has_enough_personal_guarantees(pgs_quantity) || is_save_and_continue
      message = 'The added personal guarantees have duplicate emails.'
      message += ' Please update it and try again!'

      respond_to do |format|
        format.json {
          render json: {
            apply_supplier_credit_form: nil,
            message: message
          },
          status: :unprocessable_entity
        }
      end

      return
    end

    if params['is_save_and_continue'].present?
      is_save_and_continue = CommonLib.convert_to_bool(params['is_save_and_continue'])
      @venue_supplier[:status] = Const::STATUS[:draft][:value]
    else
      is_save_and_continue = false
      trading_terms_setting = @venue_supplier.trading_terms_setting

      if trading_terms_setting[:personal_guarantees] == Const::SIGN_QUANTITIES[:none][:value]
        @venue_supplier[:status] = Const::STATUS[:no_signature_required][:value]
        @venue_supplier[:supplier_terms_condition_content] = @venue_supplier.get_supplier_terms_condition[:content]
      else
        @venue_supplier[:status] = Const::STATUS[:pending_pg_signature][:value]
      end
    end

    @apply_supplier_credit_form = @venue_supplier
    venue_credit_limit = params[:venue_credit_limit].delete(',')

    @venue_supplier.attributes = venue_supplier_params.merge(
      trading_terms_setting_id: params[:trading_terms_setting_id],
      venue_credit_limit: venue_credit_limit,
      credit_limit: venue_credit_limit
    )

    respond_to do |format|
      if @apply_supplier_credit_form.save
        apply_supplier_credit_form = @apply_supplier_credit_form.as_json

        if selected_directors_ids.present? && selected_directors_ids.count > 0
          update_directors(selected_directors_ids, @apply_supplier_credit_form, is_save_and_continue)
        elsif personal_guarantees_params.present?
          update_personal_guarantees(personal_guarantees_params, @apply_supplier_credit_form, is_save_and_continue)
        end

        save_trade_references(params, @apply_supplier_credit_form, is_save_and_continue)

        if is_save_and_continue == false
          UserMailer.ascf_apply_send_to_supplier(
            ascf: @apply_supplier_credit_form
          ).deliver_later
        end

        format.json {
          render json: {
            apply_supplier_credit_form: apply_supplier_credit_form,
            message: 'Your apply supplier credit has been updated successfully',
            redirect_url:  admin_venue_suppliers_path
          },
          status: :created
        }
      else
        format.json {
          render json: {
            apply_supplier_credit_form: nil,
            message: @apply_supplier_credit_form.errors
          },
          status: :unprocessable_entity
        }
      end
    end

    # Delete store location
    session.delete(:previous_url) if session[:previous_url].present?
  end

  def set_supplier
    @ascf = ApplySupplierCreditForm.new
    @ascf = ApplySupplierCreditForm.find(params[:ascf_id]) if params[:ascf_id].present?
    @supplier = Supplier.find(params[:supplier_id])
    venue_application_form_id = params[:venue_application_form_id]
    list_active = Supplier.available_trading_terms_settings(@supplier.id, venue_application_form_id)
    @trading_terms_active = TradingTermsSetting.where(active: true, id: list_active, supplier_id: @supplier.id)
    @supplier_terms_conditions = @supplier.supplier_terms_conditions
    @number_of_trade_references = 0

    if @trading_terms_active.where(default: true).present?
      @trading_terms_setting = @trading_terms_active.where(default: true).first
      @supplier_terms_condition = @supplier.get_terms_and_condition(venue_application_form_id, @trading_terms_setting[:id])

      @number_of_trade_references = @trading_terms_setting.get_required_trade_references_quantity
      @number_of_personal_guarantees = @trading_terms_setting.get_required_personal_guarantees_quantity
    end

app/views/admin/venue_suppliers/_apply_supplier_credit_form_actions.html.erb
<div class="m-portlet__foot m-portlet__foot--fit m--margin-top-40 ascf_form_submit">
  <div class="m-form__actions">
    <div class="row">
      <div class="col-md-2 m--align-left back-credit-2">
        <a href="#" class="btn btn-secondary m-btn m-btn--icon venue-btn-custom" data-wizard-action="prev">
          <span>
            <i class="la la-arrow-left"></i>
            &nbsp;&nbsp;
            <span>Back</span>
          </span>
        </a>
      </div>
      <div class="col-md-8 m--align-center">
        <a href="#" class="btn btn-success m-btn venue-btn-custom bt-save-continue-credit" data-wizard-action="save">
          <span>
            Save &#38; Continue Later
          </span>
        </a>
      </div>
      <div class="col-md-2 m--align-center d-flex-row-back-next">
        <div class="back-credit-1 back-next-btn-width acions-btn-width-49">
          <a href="#" class="btn btn-secondary m-btn m-btn--icon venue-btn-custom width-100p" data-wizard-action="prev">
            <span>
              <i class="la la-arrow-left"></i>
              &nbsp;&nbsp;
              <span>Back</span>
            </span>
          </a>
        </div>
        <a href="#" id="pencil-wizard-next-btn" class="btn btn-brand pencil-btn-brand m-btn m-btn--icon venue-btn-custom back-next-btn-width" data-wizard-action="next">
          <span>
            <span>
              Next
            </span>
            &nbsp;&nbsp;
            <i class="la la-arrow-right"></i>
          </span>
        </a>
        <a href="#" class="btn btn-primary m-btn venue-btn-custom m-btn--icon bt-submit-credit acions-btn-width-49 btn-submit" data-wizard-action="submit">
          <span>
            <i class="la la-check"></i>
            &nbsp;&nbsp;
            <span>Submit</span>
          </span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/admin/venue_suppliers/_apply_supplier_credit_form_step_3.html.erb
<div class="m-wizard__form-step m-wizard__form-step--current render_step_3" id="m_wizard_form_step_3">
  <div class="m-form__heading">
    <h3 class="m-form__heading-title">
      Trading Terms
    </h3>
  </div>
  <div class="row">
    <div class="col-lg-6 m--margin-bottom-20">
      <div class="row">
        <label class="col-xl-12 col-lg-12 col-form-label">
          Select Trading Terms:
        </label>
        <div class="col-xl-12 col-lg-12">
          <%
          trading_terms_setting_default = trading_terms_active.where(default: true).first

          if trading_terms_setting_default.blank?
            trading_terms_setting_default = trading_terms_active.first
          end

          if ascf.trading_terms_setting.present?
            trading_terms_setting_default = ascf.trading_terms_setting
          end
          %>
          <%= f.collection_select(:trading_terms_setting_id, trading_terms_active, :id, :trading_term,
              { selected: trading_terms_setting_default[:id] },
              { class: 'form-control m-input trading_term_selectpicker m_selectpicker width-100p',
                'data-live-search': 'true', 'data-label': 'Trading Terms' }) %>
        </div>
      </div>
    </div>
    <div class="col-lg-6 m--margin-bottom-20" id="step_3_credit_limit">
      <div class="row">
        <label class="col-xl-12 col-lg-12 col-form-label">
          Requested Credit Limit:
        </label>
        <div class="col-xl-12 col-lg-12">
          <%
            if ascf.credit_limit.present?
              credit_limit = number_to_currency(ascf.credit_limit, unit: "", separator: ".", delimiter: ",", precision: 0)
            end
          %>

          <% if credit_limits.blank? %>
            <input name="venue_credit_limit" class="form-control m-input currency text-align-left width-100p" type="text" id="venue_credit_limit_text" placeholder="Requested Credit Limit" data-label="Requested Credit Limit" value="<%= credit_limit.present? ? credit_limit : "" %>">
          <% else %>
            <%
              credit_limits_options = credit_limits.map do |increment|
                [
                  number_to_currency(increment, unit: "", separator: ".", delimiter: ",", precision: 0),
                  number_to_currency(increment, unit: "", separator: ".", delimiter: ",", precision: 0)
                ]
              end
            %>

            <%= select_tag(:venue_credit_limit, options_for_select(credit_limits_options, selected: credit_limit.present? ? credit_limit : ""), { class: 'form-control m-input credit_limits_selectpicker select_select2 width-100p', id: 'venue_credit_limit', 'data-label': 'Requested Credit Limit', style: 'width: 100%' }) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/venue_suppliers/_apply_supplier_credit_form_step_review.html.erb
<div class="m-wizard__form-step" id="m_wizard_form_step_review">
  <div class="m-form__heading">
    <h3 class="m-form__heading-title">Information Review</h3>
  </div>
  <% if is_current_pg_sign.present? && is_current_pg_sign %>
    <h3 class="text-center m--margin-bottom-30">You signed this form</h3>
  <% end %>
  <div class="form-group form-reviews"></div>
  <div class="form-group m-form__group m-form__group--sm row">
    <div class="col-xl-12">
      <div class="m-checkbox-inline">
        <%
        readonlyClass = ''
        readonlyClass = ' readonly' if is_signed
        %>
        <label class="m-checkbox m-checkbox--solid m-checkbox--brand<%= readonlyClass %>">
          <% if is_signed %>
            <input type="checkbox" name="termsConditions2" value="1"
              data-label='I have read and understand the terms and conditions'
              checked="checked" onclick="return false;">
          <% else %>
            <input type="checkbox" name="termsConditions2" value="1"
              data-label='I have read and understand the terms and conditions' class="save-later">
          <% end %>
          I have read and accept the terms and conditions above
          <span></span>
        </label>
      </div>
    </div>
  </div>
</div>

app/views/admin/venue_suppliers/_apply_supplier_credit_form_wizard_progress.html.erb
<div class="m-wizard__progress">
  <div class="progress">
    <div class="progress-bar"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>

app/views/admin/venue_suppliers/_ascf_list_trade_references.html.erb
<div data-repeater-list="trade_references" class="m-form">
  <%
  remaining_tr = number_of_trade_references - trade_references.count
  trade_references = [] if trade_references.count <= 0

  if remaining_tr > 0
    remaining_tr.times do |index|
      trade_references << TradeReference.new
    end
  else
    take_count = trade_references.count + remaining_tr
    trade_references = trade_references.take(take_count)
  end

  trade_reference_index = 0

  if trade_references.count <= 0
  %>
    <p class="no-data-message"><%= "Trade references are not required for our #{trading_terms_setting.trading_term} trading terms." %></p>
  <% end %>
  <% trade_references.each do |trade_reference| %>
    <div data-repeater-item class="trade-reference-item" data-index="<%= trade_reference_index %>">
      <h5>Trade Reference <span class="data-repeater-item-index"><%= trade_reference_index + 1 %></span></h5>
      <input type="hidden" name="id" value="<%= trade_reference[:id] %>" class="trade_reference-id">
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-md-6">
          <%= label_tag :business_name, "* Business Name", class: 'form-control-label font-weight-bold' %>
          <%= text_field_tag :business_name, trade_reference[:business_name],
            class: 'form-control m-input required', placeholder: 'Business Name',
            'data-label': 'Business Name' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-md-6">
          <%= label_tag :contact_person, "* Contact Person", class: 'form-control-label font-weight-bold' %>
          <%= text_field_tag :contact_person, trade_reference[:contact_person],
            class: 'form-control m-input required', placeholder: 'Contact Person',
            'data-label': 'Contact Person' %>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="m-form__group-sub col-md-6">
          <%= label_tag :contact_number, "* Contact Number", class: 'form-control-label font-weight-bold' %>
          <%= text_field_tag :contact_number, trade_reference[:contact_number],
            class: 'form-control m-input phoneNumber required', placeholder: 'Contact Number',
            'data-label': 'Contact Number' %>
        </div>
      </div>
      <div class="m-form__seperator m-form__seperator--dashed  m-form__seperator--space m--margin-bottom-40"></div>
    </div>
  <%
    trade_reference_index += 1
  end
  %>
</div>

app/views/admin/venue_suppliers/_form.html.erb
<%= form_with(model: venue_supplier, local: true, url: url,
  html: { class: "m-form m-form--state m-form--fit", id: "new_venue_supplier_form", name: "Newvenuesupplierform"}) do |form| %>
  <div class="m-portlet__body">
    <div class="m-form__section m-form__section--first">
      <%
      hide_error = 'm--hide'
      hide_error = '' if venue_supplier.errors.any?
      %>
      <div class="m-form__content">
        <div class="m-alert m-alert--icon alert alert-danger <%= hide_error %>" role="alert" id="m_form_1_msg">
          <div class="m-alert__icon">
            <i class="la la-warning"></i>
          </div>
          <div class="m-alert__text">
            <% if venue_supplier.errors.any? %>
              <ul>
              <% venue_supplier.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% else %>
              Oh snap! Change a few things up and try submitting again.
            <% end %>
          </div>
          <div class="m-alert__close">
            <button type="button" class="close" data-close="alert" aria-label="Close"></button>
          </div>
        </div>
      </div>
      <div class="form-group m-form__group row">
        <div class="col-lg-12">
          <%# testing %>
          <%#= form.label :venue_supplier.supplier.name, "* Trading Name:", class: 'form-control-label' %>
          <%#= form.text_field :company_name, id: :company_name, class: 'form-control m-input', placeholder: 'Trading name',:required => true %>
        </div>
      </div>
    </div>
  </div>
  <div class="m-portlet__foot m-portlet__foot--fit">
    <div class="m-form__actions m-form__actions">
      <div class="row">
        <div class="col-lg-12">
          <button id="submit_supplier" type="submit" class="btn btn-brand">
            Save
          </button>
          <button type="button" onclick="location.href='<%= admin_venue_suppliers_path %>';" class="btn btn-secondary">
            Cancel
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/venue_suppliers/_form_step_list_directors_5.html.erb
 <select class="form-control m-bootstrap-select m_selectpicker directors-select" data-label="Directors" >
  <% directors.each do |director|  %>
    <option value="<%=director.id%>" >
      <%= "#{director[:firstname]} #{director[:lastname]}" %>
    </option>
  <% end %>
</select>

app/views/admin/venue_suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_venue_supplier_path(@venue_supplier) %> |
<%= link_to 'Back', admin_venue_suppliers_path %>